### ISSUE TITLE
Post-install script error

### ISSUE THREAD

**Issue by xFilosofx** [cozy/cozy-stack#1124]
Hello, 
i have some error when tried install cozy-stack.
![image](https://user-images.githubusercontent.com/15953061/34353653-d3459c7a-ea42-11e7-984c-cb8dd20802ef.png)
Debian 9.3,  unstable and testing repo add.

**Comment by aeris** [comment]
Seems related to https://github.com/cozy/cozy-stack/pull/1128
Will release a new version this day, must fix this issue in the same time.

**Comment by yeppao** [comment]
Hello I have the same problem but with another type of error :
I followed the instructions on https://docs.cozy.io/fr/install/debian/

After the **apt install cozy-stack** step :
```bashError: Could not find config file "cozy-admin-passphrase"
dpkg: error processing package cozy-stack (--configure) :
 subprocess installed post-installation script return error exit status 1
Errors were encountered while processing:
 cozy-stack
E: Sub-process /usr/bin/dpkg returned an error code (1)
````

Debian version : 9.3

**Comment by xFilosofx** [comment]
Okay, i'm wait next release and test it.

**Comment by aeris** [comment]
Current version should works.
Check your password too, current setup code doesn't allow really strong password, advice you to only use alphanumeric password for couchdb & cozy (don't use "shell aware" characters like `&;|@` and other symbols).

**Comment by bobvador** [comment]
I have the same issue today with stable on Raspbian Stretch (RPi 3). 

I set up low level passwords (alphanumeric without capital letters)

**Comment by nono** [comment]
It has been fixed in the last published versions.

**Comment by Mistermasque** [comment]
Still have the same issue with debian buster and trying to install cozy-stack 1.4.21-1.

**Comment by KaiDevrim** [comment]
I am still getting this even on the latest version
