### ISSUE TITLE
sendmail error : timeout

### ISSUE THREAD

**Issue by tchapi** [cozy/cozy-stack#2009]
Hello

I'm using Cozy on my self hosted server and everything works fine _except_ that mails are not sent .

I have the following log : 

    time="2019-08-01T10:00:10Z" level=error msg="error while performing job: read tcp 172.22.0.3:41874->193.70.18.144:465: i/o timeout" domain=XXXXXXXXXXX job_id=f83406c1a5ce10ec65452d7fdc0018cf nspace=jobs worker_id=sendmail/0

I'm using the OVH mail SMTP (ssl0.ovh.net / ie 193.70.18.144) on port 465 for SSL, and this is my configuration : 

```
mail:
  noreply_address: noreply@mydomain.com
  noreply_name: Cozy at mydomain.com
  host: ssl0.ovh.net
  port: 465
  username: myemailadress
  password: mypassword
  disable_tls: false
  skip_certificate_validation: false
```

My email works fine, and I have tested the SMTP server too, it works fine. So I don't get why I'm having a timeout ...

The cozy stack runs inside a docker container. Do I need to open specific ports on the container for it to work ? 8080 is open of course so I can access the web interface, but do I need to open 465 too (I don't think so...) ?

Am I missing something ?
How can I debug further (I've set logs to debug but that doesn't give much more info on the error) ?

Thanks !

**Comment by tchapi** [comment]
Ok so after more investigation it seems that sending mail without TLS works (port 587) with the same SMTP server. I have another service (totally unrelated) that manages to use the TLS / 465 version of this server without problem, so it may be that cozy cannot manage TLS / or I may have misconfigured it ?

Thanks again for your help

**Comment by nono** [comment]
Cozy should be able to send emails with TLS. I don't know the configuration for OVH, maybe you can try to ask on [the forum](https://forum.cozy.io/).

**Comment by tchapi** [comment]
Thanks, I will !

**Comment by nono** [comment]
I hope this issue was fixed.

**Comment by tchapi** [comment]
Unfortunately no - so still not using TLS at the moment. Not a deal breaker, but I'm very eager to know the correct configuration or the tweak to use it correctly.
